# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout alica-plan-designer-fx
        uses: actions/checkout@v2
        with:
          repository: dasys-lab/alica-plan-designer-fx
          ref: codegen-module
          path: alica-plan-designer-fx

      - name: Build alica-plan-designer-fx
        run: mvn clean install -B -q -DskipTests
        working-directory: ${{ github.workspace }}/alica-plan-designer-fx

      - name: Checkout alica-codegen
        uses: actions/checkout@v2
        with:
          path: alica-codegen

      - name: Build alica-codegen
        run: mvn -B package --file pom.xml
        working-directory: ${{ github.workspace }}/alica-codegen

      - name: Upload alica-codegen-cpp plugin as artifact
        uses: actions/upload-artifact@v2
        with:
          name: alica-codegen-cpp
          path: ${{ github.workspace }}/alica-codegen/alica-codegen-cpp/target/codegen-cpp-1.0-SNAPSHOT.jar

      - name: Upload alica-codegen-java plugin as artifact
        uses: actions/upload-artifact@v2
        with:
          name: alica-codegen-java
          path: ${{ github.workspace }}/alica-codegen/alica-codegen-java/target/codegen-java-1.0-SNAPSHOT.jar

      - name: Upload alica-codegen-python plugin as artifact
        uses: actions/upload-artifact@v2
        with:
          name: alica-codegen-python
          path: ${{ github.workspace }}/alica-codegen/alica-codegen-python/target/codegen-python-1.0-SNAPSHOT.jar
